## Step 1: Import Required Modules

First, we need to import the necessary components from the `mitre_mapper_windows.py` script. We'll use the key functions and classes to process events programmatically.

In [11]:
import sys
from pathlib import Path
import pandas as pd

# Import components from the mitre_mapper_windows script
from mitre_mapper_windows import (
    DynamicRuleEngine,
    parse_windows_csv,
    apply_rules,
    write_csv_report
)

## Step 2: Initialize the Dynamic Rule Engine

The `DynamicRuleEngine` is the core component that:
- Fetches Sigma detection rules from GitHub (or loads from cache)
- Maps Event IDs to MITRE ATT&CK techniques
- Retrieves detailed technique information from the MITRE ATT&CK framework

**Note**: On first run, this will download rules and ATT&CK data. Subsequent runs use cached data for faster startup.

In [12]:
# Initialize the rule engine
# This will load cached rules if available, or fetch from GitHub on first run
print("Initializing Dynamic Rule Engine...")
rule_engine = DynamicRuleEngine(refresh_rules=False)  # Set to True to force refresh
print("Rule engine initialized successfully!")

Initializing Dynamic Rule Engine...
[*] Initializing MITRE ATT&CK data...
[+] MITRE ATT&CK data loaded successfully
[+] Loaded 97 Event ID mappings from cache
Rule engine initialized successfully!

## Step 3: Load and Examine Sample Security Events

Let's load the sample security events CSV file to see what we're working with. This file contains various Windows Security events that we'll enrich with MITRE ATT&CK context.

In [13]:
# Load the sample CSV file
csv_path = "TEST_SECURITY_EVENTS.csv"

# Read the original CSV to see what we're starting with
print(f"Loading events from {csv_path}...")
original_events = pd.read_csv(csv_path)
print(f"\nLoaded {len(original_events)} events")
print("\nOriginal Event IDs in the file:")
print(original_events['Event ID'].value_counts().sort_index())
print("\nFirst few events:")
original_events.head()

Loading events from TEST_SECURITY_EVENTS.csv...

Loaded 14 events

Original Event IDs in the file:
Event ID
4624    2
4625    2
4672    2
4688    2
4720    2
4726    2
7045    2
Name: count, dtype: int64

First few events:

,Date and Time,Event ID,Computer,User,Task Category,Keywords,Description
0,12/14/2025 08:00:01 AM,4624,LAB-WS01,alice,Logon,Audit Success,A user successfully logged on.
1,12/14/2025 08:01:12 AM,4625,LAB-WS01,alice,Logon,Audit Failure,An account failed to log on.
2,12/14/2025 08:02:33 AM,4688,LAB-WS01,alice,Process Creation,Audit Success,A new process has been created: C:\\Windows\\S...
3,12/14/2025 08:03:45 AM,4726,LAB-DC01,Administrator,User Account Management,Audit Success,A user account was deleted: tempuser
4,12/14/2025 08:04:50 AM,4672,LAB-DC01,Administrator,Special Logon,Audit Success,Special privileges assigned to new logon.

## Step 4: Process Events with MITRE ATT&CK Mapping

Now we'll process each event through the rule engine to enrich them with MITRE ATT&CK information. This is where the magic happens - each Event ID is matched against known attack techniques.

In [14]:
# Parse events from CSV
parsed_events = list(parse_windows_csv(csv_path))
print(f"Parsed {len(parsed_events)} events from CSV")

# Apply MITRE ATT&CK rules to each event
print("\nEnriching events with MITRE ATT&CK mappings...")
enriched_events = []
for event in parsed_events:
    enriched = apply_rules(event, rule_engine)
    enriched_events.append(enriched)

print(f"Enriched {len(enriched_events)} events")

Parsed 14 events from CSV

Enriching events with MITRE ATT&CK mappings...
Enriched 14 events

## Step 5: Analyze the Enriched Results

Let's examine what MITRE ATT&CK information was added to our events. This shows how the tool transforms raw Windows events into actionable threat intelligence.

In [15]:
# Convert to DataFrame for easier analysis
enriched_df = pd.DataFrame(enriched_events)

# Show events that were successfully mapped to MITRE ATT&CK
mapped_events = enriched_df[enriched_df['technique_id'] != '']
print(f"Events mapped to MITRE ATT&CK: {len(mapped_events)} out of {len(enriched_df)}")
print("\n" + "="*80)
print("ENRICHED EVENTS WITH MITRE ATT&CK MAPPINGS")
print("="*80)

# Display key enrichment fields
display_columns = ['timestamp', 'host', 'event_id', 'technique_id', 'technique_name', 
                  'tactic', 'severity', 'description']
mapped_events[display_columns].head(10)

Events mapped to MITRE ATT&CK: 14 out of 14

================================================================================
ENRICHED EVENTS WITH MITRE ATT&CK MAPPINGS
================================================================================

,timestamp,host,event_id,technique_id,technique_name,tactic,severity,description
0,12/14/2025 08:00:01 AM,LAB-WS01,4624,T1087,Account Discovery,Discovery,high,This events that are generated when using the ...
1,12/14/2025 08:01:12 AM,LAB-WS01,4625,T1087,Account Discovery,Discovery,high,This events that are generated when using the ...
2,12/14/2025 08:02:33 AM,LAB-WS01,4688,T1059,Command and Scripting Interpreter,Execution,medium,Adversaries may abuse command and script inter...
3,12/14/2025 08:03:45 AM,LAB-DC01,4726,T1485,Data Destruction,Impact,medium,Adversaries may destroy data and files on spec...
4,12/14/2025 08:04:50 AM,LAB-DC01,4672,T1078.003,Local Accounts,"Defense Evasion, Persistence, Privilege Escala...",high,Adversaries may obtain and abuse credentials o...
5,12/14/2025 08:06:15 AM,LAB-DC01,4720,T1136.001,Local Account,Persistence,high,Detects the creation of a local hidden user ac...
6,12/14/2025 08:07:30 AM,LAB-WS02,7045,T1021.002,SMB/Windows Admin Shares,Lateral Movement,critical,Detects known malicious service installs that ...
7,12/14/2025 08:08:50 AM,LAB-WS02,4624,T1087,Account Discovery,Discovery,high,This events that are generated when using the ...
8,12/14/2025 08:10:10 AM,LAB-WS02,4625,T1087,Account Discovery,Discovery,high,This events that are generated when using the ...
9,12/14/2025 08:11:40 AM,LAB-WS03,4688,T1059,Command and Scripting Interpreter,Execution,medium,Adversaries may abuse command and script inter...

## Step 6: Threat Intelligence Summary

Let's create a summary of the threats detected, organized by MITRE ATT&CK tactics and techniques. This demonstrates how the tool helps prioritize and understand security events.

In [16]:
# Summary by MITRE ATT&CK Tactic
print("MITRE ATT&CK TACTIC SUMMARY")
print("="*80)
tactic_summary = mapped_events.groupby('tactic').agg({
    'event_id': 'count',
    'technique_id': lambda x: ', '.join(x.unique()),
    'severity': lambda x: ', '.join(x.unique())
}).rename(columns={'event_id': 'event_count'})
tactic_summary = tactic_summary.sort_values('event_count', ascending=False)
print(tactic_summary)

print("\n" + "="*80)
print("MITRE ATT&CK TECHNIQUE SUMMARY")
print("="*80)
technique_summary = mapped_events.groupby(['technique_id', 'technique_name', 'tactic', 'severity']).size().reset_index(name='count')
technique_summary = technique_summary.sort_values('count', ascending=False)
print(technique_summary)

MITRE ATT&CK TACTIC SUMMARY
================================================================================
                                                    event_count technique_id  \
tactic
Discovery                                                     4        T1087
Defense Evasion, Persistence, Privilege Escalat...            2    T1078.003
Execution                                                     2        T1059
Impact                                                        2        T1485
Lateral Movement                                              2    T1021.002
Persistence                                                   2    T1136.001

                                                    severity
tactic
Discovery                                               high
Defense Evasion, Persistence, Privilege Escalat...      high
Execution                                             medium
Impact                                                medium
Lateral Movement                                    critical
Persistence                                             high

================================================================================
MITRE ATT&CK TECHNIQUE SUMMARY
================================================================================
  technique_id                     technique_name  \
3        T1087                  Account Discovery
0    T1021.002           SMB/Windows Admin Shares
1        T1059  Command and Scripting Interpreter
2    T1078.003                     Local Accounts
4    T1136.001                      Local Account
5        T1485                   Data Destruction

                                              tactic  severity  count
3                                          Discovery      high      4
0                                   Lateral Movement  critical      2
1                                          Execution    medium      2
2  Defense Evasion, Persistence, Privilege Escala...      high      2
4                                        Persistence      high      2
5                                             Impact    medium      2

## Step 7: Severity-Based Analysis

One of the key benefits is automatic severity assignment. Let's see how events are prioritized by severity level.

In [17]:
# Severity distribution
print("SEVERITY DISTRIBUTION")
print("="*80)
severity_counts = mapped_events['severity'].value_counts()
print(severity_counts)

# Show high and critical severity events first (most important)
print("\n" + "="*80)
print("HIGH & CRITICAL SEVERITY EVENTS (Priority Review)")
print("="*80)
high_priority = mapped_events[mapped_events['severity'].isin(['high', 'critical'])]
if len(high_priority) > 0:
    print(high_priority[['timestamp', 'host', 'event_id', 'technique_id', 
                         'technique_name', 'tactic', 'severity']].to_string(index=False))
else:
    print("No high or critical severity events found.")

SEVERITY DISTRIBUTION
================================================================================
severity
high        8
medium      4
critical    2
Name: count, dtype: int64

================================================================================
HIGH & CRITICAL SEVERITY EVENTS (Priority Review)
================================================================================
             timestamp     host event_id technique_id           technique_name                                                             tactic severity
12/14/2025 08:00:01 AM LAB-WS01     4624        T1087        Account Discovery                                                          Discovery     high
12/14/2025 08:01:12 AM LAB-WS01     4625        T1087        Account Discovery                                                          Discovery     high
12/14/2025 08:04:50 AM LAB-DC01     4672    T1078.003           Local Accounts Defense Evasion, Persistence, Privilege Escalation, Initial Access     high
12/14/2025 08:06:15 AM LAB-DC01     4720    T1136.001            Local Account                                                        Persistence     high
12/14/2025 08:07:30 AM LAB-WS02     7045    T1021.002 SMB/Windows Admin Shares                                                   Lateral Movement critical
12/14/2025 08:08:50 AM LAB-WS02     4624        T1087        Account Discovery                                                          Discovery     high
12/14/2025 08:10:10 AM LAB-WS02     4625        T1087        Account Discovery                                                          Discovery     high
12/14/2025 08:14:20 AM LAB-DC01     4672    T1078.003           Local Accounts Defense Evasion, Persistence, Privilege Escalation, Initial Access     high
12/14/2025 08:15:44 AM LAB-DC01     4720    T1136.001            Local Account                                                        Persistence     high
12/14/2025 08:17:00 AM LAB-WS03     7045    T1021.002 SMB/Windows Admin Shares                                                   Lateral Movement critical

## Step 8: Generate Comprehensive Report

Finally, let's generate a complete CSV report that can be used for further analysis, reporting, or integration with other security tools.

In [18]:
# Generate the comprehensive CSV report
output_file = "mitre_enriched_report.csv"
print(f"Generating comprehensive report: {output_file}...")

severity_counts = write_csv_report(enriched_events, output_file)

print(f"\n[+] Report written to {output_file}")
print("\n[*] Detection Summary by Severity:")
for severity in ['critical', 'high', 'medium', 'low', 'informational']:
    count = severity_counts.get(severity, 0)
    if count > 0:
        print(f"    {severity.capitalize()}: {count}")

total = sum(severity_counts.values())
print(f"    Total detections: {total}")

# Display the report
report_df = pd.read_csv(output_file)
print("\n" + "="*80)
print("COMPLETE ENRICHED REPORT (First 10 rows)")
print("="*80)
report_df.head(10)

Generating comprehensive report: mitre_enriched_report.csv...

[+] Report written to mitre_enriched_report.csv

[*] Detection Summary by Severity:
    Critical: 2
    High: 8
    Medium: 4
    Total detections: 14

================================================================================
COMPLETE ENRICHED REPORT (First 10 rows)
================================================================================

,timestamp,host,user,source,event_id,rule_id,tactic,technique_id,technique_name,severity,description,raw_message
0,12/14/2025 08:00:01 AM,LAB-WS01,alice,windows_security,4624,sigma_4624_T1087,Discovery,T1087,Account Discovery,high,This events that are generated when using the ...,Logon | Audit Success | A user successfully lo...
1,12/14/2025 08:01:12 AM,LAB-WS01,alice,windows_security,4625,sigma_4625_T1087,Discovery,T1087,Account Discovery,high,This events that are generated when using the ...,Logon | Audit Failure | An account failed to l...
2,12/14/2025 08:02:33 AM,LAB-WS01,alice,windows_security,4688,sigma_4688_T1059,Execution,T1059,Command and Scripting Interpreter,medium,Adversaries may abuse command and script inter...,Process Creation | Audit Success | A new proce...
3,12/14/2025 08:03:45 AM,LAB-DC01,Administrator,windows_security,4726,sigma_4726_T1485,Impact,T1485,Data Destruction,medium,Adversaries may destroy data and files on spec...,User Account Management | Audit Success | A us...
4,12/14/2025 08:04:50 AM,LAB-DC01,Administrator,windows_security,4672,sigma_4672_T1078.003,"Defense Evasion, Persistence, Privilege Escala...",T1078.003,Local Accounts,high,Adversaries may obtain and abuse credentials o...,Special Logon | Audit Success | Special privil...
5,12/14/2025 08:06:15 AM,LAB-DC01,Administrator,windows_security,4720,sigma_4720_T1136.001,Persistence,T1136.001,Local Account,high,Detects the creation of a local hidden user ac...,User Account Management | Audit Success | A us...
6,12/14/2025 08:07:30 AM,LAB-WS02,SYSTEM,windows_security,7045,sigma_7045_T1021.002,Lateral Movement,T1021.002,SMB/Windows Admin Shares,critical,Detects known malicious service installs that ...,Service Installation | Audit Success | A servi...
7,12/14/2025 08:08:50 AM,LAB-WS02,bob,windows_security,4624,sigma_4624_T1087,Discovery,T1087,Account Discovery,high,This events that are generated when using the ...,Logon | Audit Success | A user successfully lo...
8,12/14/2025 08:10:10 AM,LAB-WS02,bob,windows_security,4625,sigma_4625_T1087,Discovery,T1087,Account Discovery,high,This events that are generated when using the ...,Logon | Audit Failure | Multiple failed logon ...
9,12/14/2025 08:11:40 AM,LAB-WS03,charlie,windows_security,4688,sigma_4688_T1059,Execution,T1059,Command and Scripting Interpreter,medium,Adversaries may abuse command and script inter...,Process Creation | Audit Success | A new proce...

## Step 9: Deep Dive - Examining Specific Techniques

Let's examine specific MITRE ATT&CK techniques in detail to understand what they mean and why they're important.

In [19]:
# Get detailed information about a specific technique
def examine_technique(technique_id):
    """Get detailed information about a MITRE ATT&CK technique."""
    # Find events with this technique
    tech_events = mapped_events[mapped_events['technique_id'] == technique_id]
    
    if len(tech_events) == 0:
        print(f"No events found for technique {technique_id}")
        return
    
    print(f"\n{'='*80}")
    print(f"TECHNIQUE: {technique_id}")
    print(f"{'='*80}")
    
    first_event = tech_events.iloc[0]
    print(f"Technique Name: {first_event['technique_name']}")
    print(f"Tactic(s): {first_event['tactic']}")
    print(f"Severity: {first_event['severity']}")
    print(f"\nDescription:\n{first_event['description'][:500]}..." if len(str(first_event['description'])) > 500 else f"\nDescription:\n{first_event['description']}")
    
    print(f"\n\nEvents associated with this technique:")
    print(f"Total: {len(tech_events)}")
    print(tech_events[['timestamp', 'host', 'event_id', 'user', 'raw_message']].to_string(index=False))

# Examine some of the techniques we found
unique_techniques = mapped_events['technique_id'].unique()
print(f"\nFound {len(unique_techniques)} unique MITRE ATT&CK techniques")
print(f"Techniques: {', '.join(unique_techniques)}")

# Examine the first technique in detail
if len(unique_techniques) > 0:
    examine_technique(unique_techniques[0])

Found 6 unique MITRE ATT&CK techniques
Techniques: T1087, T1059, T1485, T1078.003, T1136.001, T1021.002

================================================================================
TECHNIQUE: T1087
================================================================================
Technique Name: Account Discovery
Tactic(s): Discovery
Severity: high

Description:
This events that are generated when using the hacktool Ruler by Sensepost

Technique: Adversaries may attempt to get a listing of valid accounts, usernames, or email addresses on a system or within a compromised environment. This information can help adversaries determine which accounts exist, which can aid in follow-on behavior such as brute-forcing, spear-phishing attacks, or account takeovers (e.g., [Valid Accounts](https://attack.mitre.org/techniques/T1078)).

Adversaries may use several met...


Events associated with this technique:
Total: 4
             timestamp     host event_id  user                                                      raw_message
12/14/2025 08:00:01 AM LAB-WS01     4624 alice           Logon | Audit Success | A user successfully logged on.
12/14/2025 08:01:12 AM LAB-WS01     4625 alice             Logon | Audit Failure | An account failed to log on.
12/14/2025 08:08:50 AM LAB-WS02     4624   bob           Logon | Audit Success | A user successfully logged on.
12/14/2025 08:10:10 AM LAB-WS02     4625   bob Logon | Audit Failure | Multiple failed logon attempts detected.

## Step 10: Understanding the Benefits - Before and After Comparison

Let's compare the original events with the enriched events to clearly see the value added by the MITRE mapper.

In [20]:
print("BEFORE: Original Event (Limited Context)")
print("="*80)
print(f"Event ID: {original_events.iloc[0]['Event ID']}")
print(f"Description: {original_events.iloc[0]['Description']}")
print(f"\nWhat does this mean? An analyst would need to:")
print("  1. Look up Event ID 4624 in Microsoft documentation")
print("  2. Understand what this event indicates")
print("  3. Determine if it's related to known attack patterns")
print("  4. Manually assess severity and priority")

print("\n\nAFTER: Enriched Event (Actionable Threat Intelligence)")
print("="*80)
enriched_sample = mapped_events.iloc[0] if len(mapped_events) > 0 else enriched_df.iloc[0]
print(f"Event ID: {enriched_sample['event_id']}")
print(f"MITRE ATT&CK Technique: {enriched_sample['technique_id']} - {enriched_sample['technique_name']}")
print(f"Tactic: {enriched_sample['tactic']}")
print(f"Severity: {enriched_sample['severity']}")
print(f"\nDescription: {enriched_sample['description'][:300]}..." if len(str(enriched_sample['description'])) > 300 else f"\nDescription: {enriched_sample['description']}")

print("\n\nValue Added:")
print("  ✓ Immediate threat context (what attack technique this represents)")
print("  ✓ Automatic severity assignment (prioritization)")
print("  ✓ Standardized framework alignment (MITRE ATT&CK)")
print("  ✓ Detailed technique description (no manual lookup needed)")
print("  ✓ Tactic classification (attack phase identification)")

BEFORE: Original Event (Limited Context)
================================================================================
Event ID: 4624
Description: A user successfully logged on.

What does this mean? An analyst would need to:
  1. Look up Event ID 4624 in Microsoft documentation
  2. Understand what this event indicates
  3. Determine if it's related to known attack patterns
  4. Manually assess severity and priority


AFTER: Enriched Event (Actionable Threat Intelligence)
================================================================================
Event ID: 4624
MITRE ATT&CK Technique: T1087 - Account Discovery
Tactic: Discovery
Severity: high

Description: This events that are generated when using the hacktool Ruler by Sensepost

Technique: Adversaries may attempt to get a listing of valid accounts, usernames, or email addresses on a system or within a compromised environment. This information can help adversaries determine which accounts exist, which...


Value Added:
  ✓ Immediate threat context (what attack technique this represents)
  ✓ Automatic severity assignment (prioritization)
  ✓ Standardized framework alignment (MITRE ATT&CK)
  ✓ Detailed technique description (no manual lookup needed)
  ✓ Tactic classification (attack phase identification)

## Key Takeaways

### Why This Tool is Valuable for Security Operations

1. **Time Savings**: Automates the manual process of looking up Event IDs and understanding their security implications

2. **Consistency**: Provides standardized threat intelligence context using the industry-standard MITRE ATT&CK framework

3. **Prioritization**: Automatically assigns severity levels to help analysts focus on the most critical events first

4. **Scalability**: Can process thousands of events efficiently, making it practical for enterprise environments

5. **Threat Intelligence Integration**: Connects raw Windows events to known attack patterns, enabling proactive threat hunting

6. **Detection Engineering**: Helps security teams understand which events map to which attack techniques, improving detection coverage

7. **Reporting**: Generates structured reports that can be integrated into SIEM systems, ticketing systems, or security dashboards

8. **Continuous Updates**: Dynamic rule engine stays current with emerging threats through the Sigma repository

### Use Cases

- **Security Incident Response**: Quickly understand what attack techniques are present in event logs
- **Threat Hunting**: Identify patterns of MITRE ATT&CK techniques across large datasets
- **Detection Engineering**: Map existing events to ATT&CK techniques to identify detection gaps
- **Security Reporting**: Generate standardized threat intelligence reports for stakeholders
- **SIEM Enrichment**: Enrich events in SIEM systems with MITRE ATT&CK context
- **Forensic Analysis**: Understand the attack chain by mapping events to ATT&CK tactics

### Next Steps

1. Process your own Windows Security event logs
2. Integrate the script into automated security workflows
3. Customize severity mappings based on your organization's risk profile
4. Use the enriched reports for threat hunting and detection engineering
5. Schedule regular processing to maintain continuous security monitoring

---

**Note**: This tool is designed for security automation and threat intelligence. Always validate detections and consider false positives in your specific environment.